---
---
 
On this page, you will find information about our paired word norms used in our projects. We have split our single and paired word norms into two separate databases to speed database processing time for the user. Word pair norms are cue-target groupings that require both concepts to be included to understand the relation between these concepts. For example, cat-dog can be understood in context of association (i.e., it's raining cats and dogs) or though semantics (i.e., cats and dogs have many similar features). This dataset includes all cues-target pairings from the Buchanan et al. (2012) semantic word-pair norms, our extension project ([OSF](https://osf.io/cjyzw/),  [GitHub](https://github.com/doomlab/Word-Norms-2)), and their overlap with the McRae, Cree, Seidenberg, and McNorgan (2005) and Vinson and Vigliocco (2008) norms. If two concepts are included in the dataset, but do not appear together as a row on this site, you can assume their feature overlap is very close to or zero. We calculated these cosine values for pairs that included at least two features in common. With over 4000 pairs, the possible combinations are 16+ million, and therefore, we used this restriction to give word pair combinations that were effectively non-zero while still being able to view and manipulate the database. When downloading the applications to run locally on RStudio, please be sure to download the dataset in the main [GitHub repository](https://github.com/doomlab/shiny-server/tree/master/lab).

## Variable Table

You can view the complete variable table that lists the variables, their descriptions, min, max, mean, and standard deviation. Norms are taken from the University of South Florida Free Association Norms (Nelson, McEvoy, & Schreiber, 2004), JCN semantic dictionary distance (Maki, McKinley, & Thompson, 2004; Maki, 2008), and LSA values (Landauer & Dumais, 1997).

This [link](http://96.242.30.151:3838/lab/double_var_table) will take to the Shiny app that calculates the statistics based on the current dataset. Please contact us if the link or any others below are not loading. [Download](https://github.com/doomlab/shiny-server/tree/master/lab/double_var_table) this app to run locally.

## View and Search the Words

You can use the [Shiny app](http://96.242.30.151:3838/lab/double_words/) provided to view all the words and their information. The top boxes in this datatable allow you to filter the columns for specific ranges you might be interested in. This app does load slowly because it is 200,000+ lines, so please be patient. [Download](https://github.com/doomlab/shiny-server/tree/master/lab/double_words) this app to run locally.

## Download the Data

You can download the csv file of the single word information [here](https://github.com/doomlab/shiny-server/blob/master/lab/double_words.csv).